### ISSUE TITLE
Phase 2: Regular User Module

### ISSUE THREAD

**Issue by adrianreza96** [adrianreza96/team1#13]
With Phase 1, we should have all the Kitchen data available in the database, in this phase of the
application, we will display Kitchen information to end-users so that they can place an order by
selecting a menu item from the kitchen provider’s list.

- [ ] .1. When user browse the application, they will see a page having listed all the

REGISTERED kitchens in this format:
![registeredKitchensFormat.PNG](https://images.zenhubusercontent.com/58f2506951aa2c30577b6add/396f6c97-15ad-45dd-846d-2dedbe3e7318)
- [ ] .2. All the Kitchen Images will be clickable and once clicked, it will redirect the user to another screen which will show the Menu for that Kitchen along with prices.
- [ ] .3. Each menu item should have a checkbox next to it with “add to cart” and a button at the bottom with the display name “Add”.
- [ ] .4. Once user checks the checkboxes and clicks on “Add”, all the items should be added to the cart.
- [ ] .5. User should be able to register & Login himself/herself by clicking on user icon which is available.
- [ ] .6. If the user is logged in, application will display his/her name.
- [ ] .7. User Registration screen is a standard screen with options such as first name, last name, email, password and two security questions and answers.
