### ISSUE TITLE
Phase 1: Service Provider Module

### ISSUE THREAD

**Issue by adrianreza96** [adrianreza96/team1#3]
This module will allow a service provider to register his/her kitchen using a registration
screen. Here are the primary functions of this module:
- [ ] .1. Allow a Kitchen to register on the application using a “Provider Register Now” Link at
the top section of the application. Once clicked, it will open a screen with these
entry/selection options:

- [ ] .2. a. Service Provider Name (Unique varchar (50) Not NULL): This will be displayed
 to end user at the time of creation of an order.

> - [ ] .b. Email(Unique varchar(50) Not NULL)
- [ ] . c. Password nVarchar(10) NOT NULL
- [ ] .d. Confirm Password nVarchar(10) NOT NULL
- [ ] . e. Next Button
- [ ] .f. Cancel Button

- [ ] .3. When clicked on cancel button, user will be redirected to application landing screen
without saving any data.
 - [ ] .4. When clicked on Next button, here is what user will see:
> - [ ] .a. Kitchen working Days: checkbox selections for Monday to Sunday
>- [ ] .b. Kitchen working Time: two dropdown Start Time and End Time.
>- [ ] .c. Kitchen Image: browse control to upload an image. This image will be shown at
kitchen display.
>- [ ] .d. Kitchen Menu. One Kitchen will have more than one Menu Item and each

Menu Item will have these attributes:
>- [ ].i. Item Name
- [ ].ii. Veg/Non-Veg
- [ ].iii. Price.
- [ ].e. Save Button
- [ ].f. Cancel Button

- [ ] .5. Once user register, they should see a success message.
